title: Villavis
email: info@villaviscuracao.com
description: "Visrestaurant & Sushi - Curaçao, Sushi restaurant, verse vis, visrestaurant, online bestellen, afhalen"
baseurl: "" 
url: "https://www.villaviscuracao.com" # jouw domein
languages:
  - nl
  - en

